#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf 0 > /dev/null 2>&1

cleanCase

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=$(getApplication)

runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication topoSet
# runApplication subsetMesh -overwrite c0 -patch floatingObject -noFields
cp -r 0.orig 0 > /dev/null 2>&1
runApplication setFields
runApplication $application

#------------------------------------------------------------------------------
