#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf 0 > /dev/null 2>&1

cleanCase

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=$(getApplication)

# runApplication blockMesh
# runApplication surfaceFeatureExtract
# runApplication snappyHexMesh -overwrite
# runApplication extrudeMesh
cp -r 0.orig 0 > /dev/null 2>&1
cp -r "./backups/polyMesh.$1" ./constant/polyMesh > /dev/null 2>&1 #
runApplication setFields
touch tmp.foam
runApplication $application
# runApplication decomposePar
# mpirun -oversubscribe -np 16 $application -parallel | tee "log.$application" > /dev/null 2>&1
# runApplication reconstructPar

# ------------------------------------------------------------------------------
